/* POPOLAZIONE */

insert into Country (Name) values ('Afghanistan');
insert into Country (Name) values ('Albania');
insert into Country (Name) values ('Algeria');
insert into Country (Name) values ('Andorra');
insert into Country (Name) values ('Angola');
insert into Country (Name) values ('Antigua and Barbuda');
insert into Country (Name) values ('Argentina');
insert into Country (Name) values ('Armenia');
insert into Country (Name) values ('Australia');
insert into Country (Name) values ('Austria');
insert into Country (Name) values ('Azerbaijan');
insert into Country (Name) values ('Bahamas');
insert into Country (Name) values ('Bahrain');
insert into Country (Name) values ('Bangladesh');
insert into Country (Name) values ('Barbados');
insert into Country (Name) values ('Belarus');
insert into Country (Name) values ('Belgium');
insert into Country (Name) values ('Belize');
insert into Country (Name) values ('Benin');
insert into Country (Name) values ('Bhutan');
insert into Country (Name) values ('Bolivia');
insert into Country (Name) values ('Bosnia and Herzegovina');
insert into Country (Name) values ('Botswana');
insert into Country (Name) values ('Brazil');
insert into Country (Name) values ('Brunei');
insert into Country (Name) values ('Bulgaria');
insert into Country (Name) values ('Burkina Faso');
insert into Country (Name) values ('Burundi');
insert into Country (Name) values ('Côte d''Ivoire');
insert into Country (Name) values ('Cabo Verde');
insert into Country (Name) values ('Cambodia');
insert into Country (Name) values ('Cameroon');
insert into Country (Name) values ('Canada');
insert into Country (Name) values ('Central African Republic');
insert into Country (Name) values ('Chad');
insert into Country (Name) values ('Chile');
insert into Country (Name) values ('China');
insert into Country (Name) values ('Colombia');
insert into Country (Name) values ('Comoros');
insert into Country (Name) values ('Congo');
insert into Country (Name) values ('Costa Rica');
insert into Country (Name) values ('Croatia');
insert into Country (Name) values ('Cuba');
insert into Country (Name) values ('Cyprus');
insert into Country (Name) values ('Czechia');
insert into Country (Name) values ('Democratic Republic of the Congo');
insert into Country (Name) values ('Denmark');
insert into Country (Name) values ('Djibouti');
insert into Country (Name) values ('Dominica');
insert into Country (Name) values ('Dominican Republic');

